# Application
spring.application.name=exakt-vvip
server.port=8080

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://dbms-database-1.cluster-crggeo8kio6t.ap-southeast-1.rds.amazonaws.com:3306/dci_ctpl?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Manila
spring.datasource.username=admin
spring.datasource.password=HsM0gcqEUIa4YDHo78TQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=vVIP-ExAKT-2026-SuperSecretKey-DoNotExpose-InProductionChangeThis-vVIP-ExAKT
app.jwt.expiration-ms=86400000


# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# VVS API
vvs.api.base-url=https://stg-prmisapi.onlinelto.ph/vvis/api
vvs.api.provider-code=DCI20250001
vvs.api.api-key=PK-DCI20250001-1025  
vvs.api.connect-timeout=5000
vvs.api.read-timeout=10000
#vvs.api.pfx-path=classpath:certs/smccert_07102025.pfx
#vvs.api.pfx-password=smccertnew071025
## Temporary ? remove after debugging
#logging.level.org.apache.hc=DEBUG

# VVIP Certificate
#vvip.certificate.output-dir=/var/app/dci-certificates
vvip.certificate.output-dir=C:/vvip-certificates
vvip.certificate.validity-days=365
vvip.certificate.dotr-logo-path=classpath:logos/dotr_logo.png
vvip.certificate.vvs-logo-path=classpath:logos/vvs_logo.png
