# Application
spring.application.name=dci-clearance
server.port=8080

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://dbms-database-1.cluster-crggeo8kio6t.ap-southeast-1.rds.amazonaws.com:3306/dciclearance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Manila&zeroDateTimeBehavior=convertToNull
spring.datasource.username=admin
spring.datasource.password=HsM0gcqEUIa4YDHo78TQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
server.error.include-binding-errors=always
server.error.include-message=always

# JWT
app.jwt.secret=DCI-CLEARANCE-2026-SuperSecretKey-DoNotExpose-InProductionChangeThis-DCI
app.jwt.expiration-ms=86400000


# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# VVS API
vvs.api.base-url=https://stg-prmisapi.onlinelto.ph/vvis/api
vvs.api.provider-code=DCI20250001
vvs.api.api-key=PK-DCI20250001-1025
vvs.api.connect-timeout=5000
vvs.api.read-timeout=10000

# TLPE API
tlpe.api.payment=https://test-webapi.tlpe.io/transaction/pay?token=Bearer%20eyJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiIyNGVkZmU5Yy1iZTU5LTRkNGUtOGZhNS1kMmQ4MmE5ZTQ1YzEiLCJ0eXBlIjoiRFlOQU1JQyJ9.40qzHwexC9S0aYVCGTK_gkgSL-J9fShv4E2iDg4drZs
tlpe.api.authKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMOfruVNnrAfOCTVvz5DwQIn6by6iSc43awzjzQzrzWLSXFqmORTV4ySRqB20c+33biEppjbEGN6sk4/IN0+K2MCAwEAAQ==

merchant-callback.webhook-signing-secret=MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAugpxV9yGOA8EAKsSjSqUH85ndEcRP/BEvl6to8qkS98QFJ8Y8J/pL0ZKSX1DLi4oV/m2JY1AqdA9SENzDgXPMwIDAQABAkBaOzph7NlEUzQTxuVGhoI1MvzGTrm1EymkU3NQX7Zz/TZAMQNZh/Yn+DD8mfDkUTN5wM9Rre450bwLk2w1ew6xAiEA6PKKhyMtzkKXH8l8Dn6SUWBxNBIiUGVT77Klg31tdqcCIQDMc5NCrVD9fw1jc1YpeRE35T+pDXbDKvzDYsDHTepAlQIgGop/5BPLBUQrCdEgFFqxexoc68zhIf3ZiWb2Wrvwu+MCIFC0drblT4khdBmD18k7Py6/UefbprvX5jsCanLCMOwZAiA0rYNZ6rCncrSLSEc3DoVG4xTXvXc0yjRdee2pndM1qw==
merchant-callback.tlpe-api-base-url=https://test-api.tlpe.io
merchant-callback.integrator-token=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMOfruVNnrAfOCTVvz5DwQIn6by6iSc43awzjzQzrzWLSXFqmORTV4ySRqB20c+33biEppjbEGN6sk4/IN0+K2MCAwEAAQ==

merchant-callback.billero-redeem-url=https://test-edc-api.billeroo.com/voucher/redeem
merchant-callback.billero-api-base-url=https://test-edc-api.billeroo.com/voucher/confirm-payment
merchant-callback.billero-token=BPU4MGCq5FFZhLZovK$E2$ZQ6Ba7T5qy=JKKnXgEEn4c8c/Q@xN5rgITTF=UHu1zL2SP75BCaAmmJCQAki48ssMiYGNXK2@t5M3uoAzkq0ZhXWJQ==